import { MigrationInterface, QueryRunner, Table, TableIndex } from 'typeorm';

export default class tblB3SpotexchangeIntraday1632950199755
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'b3-spotexchange-intraday',
        columns: [
          {
            name: 'date',
            type: 'date',
            isNullable: false,
          },
          {
            name: 'timestamp-load',
            type: 'timestamptz',
            isNullable: false,
          },
          {
            name: 'currency-code',
            type: 'text',
            isNullable: false,
          },
          {
            name: 'time08-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time08-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time08-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time08-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time09-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time09-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time09-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time09-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time10-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time10-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time10-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time10-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time11-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time11-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time11-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time11-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time12-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time12-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time12-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time12-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time13-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time13-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time13-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time13-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time14-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time14-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time14-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time14-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time15-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time15-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time15-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time15-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time16-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time16-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time16-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time16-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time17-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time17-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time17-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time17-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time18-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time18-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time18-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time18-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time19-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time19-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time19-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'time19-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'total-finVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: false,
            unsigned: true,
          },
          {
            name: 'total-qtyTrades',
            type: 'int',
            isNullable: false,
            unsigned: true,
          },
          {
            name: 'tcam',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: false,
            unsigned: true,
          },
        ],
      }),
    );

    await queryRunner.createIndex(
      'b3-spotexchange-intraday',
      new TableIndex({
        name: '503518cc-113b-4a25-903c-66079791c33d',
        columnNames: ['date'],
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropIndex(
      'b3-spotexchange-intraday',
      '503518cc-113b-4a25-903c-66079791c33d',
    );
    await queryRunner.dropTable('b3-spotexchange-intraday');
  }
}
