import { MigrationInterface, QueryRunner, Table, TableIndex } from 'typeorm';

export default class tblB3Spotexchange1632975323785
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'b3-spotexchange',
        columns: [
          {
            name: 'date',
            type: 'date',
            isNullable: false,
          },
          {
            name: 'timestamp-load',
            type: 'timestamptz',
            isNullable: false,
          },
          {
            name: 'currency-code',
            type: 'text',
            isNullable: false,
          },
          {
            name: 'avgrate-hiringdate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'avgrate-d0-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'avgrate-d0-tcam',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'avgrate-d1-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'avgrate-d1-tcam',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'avgrate-d2-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'avgrate-d2-tcam',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-hiringdate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'hiringrate-d0-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'hiringrate-d0-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-d0-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-d0-close',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-d1-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'hiringrate-d1-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-d1-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-d1-close',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-d2-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'hiringrate-d2-low',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-d2-high',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringrate-d2-close',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-hiringdate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'hiringvol-d0-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'hiringvol-d0-foreignFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-d0-brlFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-d0-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-d1-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'hiringvol-d1-foreignFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-d1-brlFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-d1-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-d2-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'hiringvol-d2-foreignFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-d2-brlFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-d2-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-total-foreignFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-total-brlFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'hiringvol-total-qtyTrades',
            type: 'int',
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'settletrans-d0-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'settletrans-d0-foreignFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'settletrans-d0-brlFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'settletrans-d1-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'settletrans-d1-foreignFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'settletrans-d1-brlFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'settletrans-d2-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'settletrans-d2-foreignFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'settletrans-d2-brlFinVol',
            type: 'numeric',
            precision: 15,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'openparams-hiringdate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'openparams-d0-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'openparams-d0-stressrisk',
            type: 'numeric',
            precision: 5,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'openparams-d0-openrate',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'openparams-d1-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'openparams-d1-stressrisk',
            type: 'numeric',
            precision: 5,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'openparams-d1-openrate',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'openparams-d2-settledate',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'openparams-d2-stressrisk',
            type: 'numeric',
            precision: 5,
            scale: 2,
            isNullable: true,
            unsigned: true,
          },
          {
            name: 'openparams-d2-openrate',
            type: 'numeric',
            precision: 9,
            scale: 4,
            isNullable: true,
            unsigned: true,
          },
        ],
      }),
    );

    await queryRunner.createIndex(
      'b3-spotexchange',
      new TableIndex({
        name: '30fc0ce2-daff-4811-9d3e-21731f1849e2',
        columnNames: ['date'],
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropIndex(
      'b3-spotexchange',
      '30fc0ce2-daff-4811-9d3e-21731f1849e2',
    );

    await queryRunner.dropTable('b3-spotexchange');
  }
}
